databases:
  - name: eventos-hackathon-db
    plan: free
    region: oregon

services:
  - type: web
    name: eventos-hackathon
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: APP_NAME
        value: Eventos Hackathon TecNM
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: eventos-hackathon-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: eventos-hackathon-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: eventos-hackathon-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: eventos-hackathon-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: eventos-hackathon-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp-relay.brevo.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: eventos.contacto.web@gmail.com
      - key: MAIL_PASSWORD
        value: lxxx gyrq bgrn ubty
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: eventos.contacto.web@gmail.com
      - key: MAIL_FROM_NAME
        value: Eventos Hackathon TecNM
